version: '3'
services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: 'listen --api-key ${STRIPE_SECRET_KEY} --forward-to localhost:3000/api/webhook'
    env_file:
      - .env
