version: '3'
services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
    env_file:
      - .env
    expose:
      - 5432

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: 'listen --api-key ${STRIPE_SECRET_KEY} --forward-to http://localhost:3000/api/webhook'
    env_file:
      - .env

  nextjs:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - db

  prisma-studio:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    command: npx prisma studio
    ports:
      - '5555:5555'
    environment:
      POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
    depends_on:
      - db
