version: '3'
services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
    env_file:
      - .env
    expose:
      - 5432

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_DEVICE_NAME: 'f355e87f75fd'
    command: 'listen --api-key ${STRIPE_SECRET_KEY} --forward-to http://host.docker.internal:3000/api/webhook'
    env_file:
      - .env
