version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: 'listen --api-key ${STRIPE_SECRET_KEY} --forward-to localhost:3000/api/webhook'
    env_file:
      - .env
